base_url = "https://jimmillerdrums.com"
title = "Jim Miller Drums"
description = "NYC Session & Live Drummer"
default_language = "en"
compile_sass = false
build_search_index = false

[extra]
email = "contact@jimmillerdrums.com"
social_media = [
  { 
    name = "Instagram", 
    url = "https://instagram.com/jimmillerdrums", 
    icon_path = "M12 0C8.74 0 8.333.015 7.053.072 5.775.132 4.905.333 4.14.63c-.789.306-1.459.717-2.126 1.384S.935 3.35.63 4.14C.333 4.905.131 5.775.072 7.053.012 8.333 0 8.74 0 12s.015 3.667.072 4.947c.06 1.277.261 2.148.558 2.913.306.788.717 1.459 1.384 2.126.667.666 1.336 1.079 2.126 1.384.766.296 1.636.499 2.913.558C8.333 23.988 8.74 24 12 24s3.667-.015 4.947-.072c1.277-.06 2.148-.262 2.913-.558.788-.306 1.459-.718 2.126-1.384.666-.667 1.079-1.335 1.384-2.126.296-.765.499-1.636.558-2.913.06-1.28.072-1.687.072-4.947s-.015-3.667-.072-4.947c-.06-1.277-.262-2.149-.558-2.913-.306-.789-.718-1.459-1.384-2.126C21.319 1.347 20.651.935 19.86.63c-.765-.297-1.636-.499-2.913-.558C15.667.012 15.26 0 12 0zm0 2.16c3.203 0 3.584.016 4.85.071 1.17.054 1.805.249 2.227.412.56.216.96.472 1.381.893.42.42.677.82.893 1.38.164.423.358 1.058.413 2.227.057 1.266.07 1.646.07 4.85s-.015 3.584-.071 4.85c-.054 1.17-.249 1.805-.412 2.227-.216.56-.472.96-.893 1.38-.42.42-.82.677-1.38.893-.423.164-1.058.358-2.227.413-1.266.057-1.646.07-4.85.07s-3.584-.015-4.85-.071c-1.17-.054-1.805-.249-2.227-.412a3.486 3.486 0 0 1-1.381-.893 3.49 3.49 0 0 1-.893-1.38c-.164-.423-.358-1.058-.413-2.227-.057-1.266-.07-1.646-.07-4.85s.016-3.584.071-4.85c.054-1.17.249-1.805.412-2.227.216-.56.472-.96.893-1.381.42-.42.82-.677 1.38-.893.423-.164 1.058-.358 2.227-.413 1.266-.057 1.646-.07 4.85-.07zM12 5.838a6.162 6.162 0 1 0 0 12.324 6.162 6.162 0 0 0 0-12.324zM12 16a4 4 0 1 1 0-8 4 4 0 0 1 0 8zm6.406-11.845a1.44 1.44 0 1 0 0 2.881 1.44 1.44 0 0 0 0-2.881z" 
  },
  { name = "YouTube",
    url = "https://youtube.com/@jimmillerdrums",
    icon_path = "M23.498 6.186a3.016 3.016 0 0 0-2.122-2.136C19.505 3.545 12 3.545 12 3.545s-7.505 0-9.377.505A3.017 3.017 0 0 0 .502 6.186C0 8.07 0 12 0 12s0 3.93.502 5.814a3.016 3.016 0 0 0 2.122 2.136c1.871.505 9.376.505 9.376.505s7.505 0 9.377-.505a3.015 3.015 0 0 0 2.122-2.136C24 15.93 24 12 24 12s0-3.93-.502-5.814zM9.545 15.568V8.432L15.818 12l-6.273 3.568z" 
  },
  { name = "Bluesky",
    url = "https://bsky.app/profile/drumjimdrum.bsky.social",
    icon_path = "M 5.429688 1.992188 C 8.089844 4.253906 10.949219 8.835938 12 11.296875 C 13.050781 8.839844 15.910156 4.253906 18.570312 1.992188 C 20.492188 0.363281 23.601562 -0.898438 23.601562 3.117188 C 23.601562 3.917969 23.195312 9.855469 22.957031 10.816406 C 22.128906 14.167969 19.109375 15.023438 16.425781 14.503906 C 21.117188 15.410156 22.3125 18.402344 19.734375 21.398438 C 14.835938 27.085938 12.695312 19.972656 12.148438 18.148438 C 12.046875 17.8125 12 17.65625 12 17.792969 C 12 17.65625 11.953125 17.8125 11.851562 18.148438 C 11.304688 19.972656 9.164062 27.085938 4.265625 21.398438 C 1.6875 18.402344 2.882812 15.410156 7.574219 14.503906 C 4.890625 15.023438 1.871094 14.167969 1.042969 10.816406 C 0.804688 9.855469 0.398438 3.917969 0.398438 3.117188 C 0.398438 -0.898438 3.507812 0.363281 5.429688 1.992188 Z M 5.429688 1.992188 "
  }
]
status_enabled = true
status_text = "currently rehearsing // new material"
status_color_class = "bg-[#2563EB]"
status_text_class = "text-zinc-500"
