base_url = "https://jimmillerdrums.com"
title = "Jim Miller Drums"
description = "NYC Session & Live Drummer"
default_language = "en"
compile_sass = false
build_search_index = false

[extra]
email = "contact@jimmillerdrums.com"
social_media = [
  { name = "Instagram", url = "https://instagram.com/jimmillerdrums" },
  { name = "YouTube", url = "https://youtube.com/@jimmillerdrums" },
  { name = "Bluesky", url = "https://bsky.app/profile/drumjimdrum.bsky.social" }
]
