- name: Install Zola
        uses: taiki-e/install-action@v2
        with:
          tool: zola

      - name: Build Website
        run: zola build
        working-directory: ./site

      - name: Deploy to S3
        # We change the source from 'site/' to 'site/public/'
        run: aws s3 sync site/public/ s3://${{ secrets.S3_BUCKET_NAME }} --delete

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_ID }} --paths "/*"